# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1872, 632)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(300, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.controlsWidget = QtWidgets.QWidget(self.centralwidget)
        self.controlsWidget.setMinimumSize(QtCore.QSize(900, 594))
        self.controlsWidget.setMaximumSize(QtCore.QSize(900, 16777215))
        self.controlsWidget.setObjectName("controlsWidget")
        self.controlFrame = QtWidgets.QFrame(self.controlsWidget)
        self.controlFrame.setGeometry(QtCore.QRect(20, 426, 851, 167))
        self.controlFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.controlFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.controlFrame.setObjectName("controlFrame")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.controlFrame)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.controlWidget = QtWidgets.QWidget(self.controlFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controlWidget.sizePolicy().hasHeightForWidth())
        self.controlWidget.setSizePolicy(sizePolicy)
        self.controlWidget.setMinimumSize(QtCore.QSize(0, 80))
        self.controlWidget.setObjectName("controlWidget")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.controlWidget)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.volumeVerticalLayout = QtWidgets.QVBoxLayout()
        self.volumeVerticalLayout.setObjectName("volumeVerticalLayout")
        self.volumeLabel = QtWidgets.QLabel(self.controlWidget)
        self.volumeLabel.setObjectName("volumeLabel")
        self.volumeVerticalLayout.addWidget(self.volumeLabel)
        self.volumeSpinBox = QtWidgets.QSpinBox(self.controlWidget)
        self.volumeSpinBox.setMinimumSize(QtCore.QSize(0, 30))
        self.volumeSpinBox.setMaximum(200)
        self.volumeSpinBox.setProperty("value", 100)
        self.volumeSpinBox.setObjectName("volumeSpinBox")
        self.volumeVerticalLayout.addWidget(self.volumeSpinBox)
        self.horizontalLayout_15.addLayout(self.volumeVerticalLayout)
        self.delayVerticalLayout = QtWidgets.QVBoxLayout()
        self.delayVerticalLayout.setObjectName("delayVerticalLayout")
        self.delayLabel = QtWidgets.QLabel(self.controlWidget)
        self.delayLabel.setObjectName("delayLabel")
        self.delayVerticalLayout.addWidget(self.delayLabel)
        self.delaySpinBox = QtWidgets.QSpinBox(self.controlWidget)
        self.delaySpinBox.setMinimumSize(QtCore.QSize(0, 30))
        self.delaySpinBox.setMaximum(60000)
        self.delaySpinBox.setObjectName("delaySpinBox")
        self.delayVerticalLayout.addWidget(self.delaySpinBox)
        self.horizontalLayout_15.addLayout(self.delayVerticalLayout)
        self.emptyWidget = QtWidgets.QWidget(self.controlWidget)
        self.emptyWidget.setObjectName("emptyWidget")
        self.horizontalLayout_15.addWidget(self.emptyWidget)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.startEmptyLabel = QtWidgets.QLabel(self.controlWidget)
        self.startEmptyLabel.setText("")
        self.startEmptyLabel.setObjectName("startEmptyLabel")
        self.verticalLayout_16.addWidget(self.startEmptyLabel)
        self.addEffectButton = QtWidgets.QPushButton(self.controlWidget)
        self.addEffectButton.setMinimumSize(QtCore.QSize(0, 30))
        self.addEffectButton.setObjectName("addEffectButton")
        self.verticalLayout_16.addWidget(self.addEffectButton)
        self.horizontalLayout_15.addLayout(self.verticalLayout_16)
        self.horizontalLayout_14.addWidget(self.controlWidget)
        self.tabWidget = QtWidgets.QTabWidget(self.controlsWidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 244, 851, 148))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setObjectName("tabWidget")
        self.transposeTab = QtWidgets.QWidget()
        self.transposeTab.setObjectName("transposeTab")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.transposeTab)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.intervalSplitter = QtWidgets.QSplitter(self.transposeTab)
        self.intervalSplitter.setOrientation(QtCore.Qt.Vertical)
        self.intervalSplitter.setObjectName("intervalSplitter")
        self.intervalLabel = QtWidgets.QLabel(self.intervalSplitter)
        self.intervalLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.intervalLabel.setObjectName("intervalLabel")
        self.intervalSpinBox = QtWidgets.QSpinBox(self.intervalSplitter)
        self.intervalSpinBox.setMinimumSize(QtCore.QSize(100, 30))
        self.intervalSpinBox.setMaximumSize(QtCore.QSize(16777215, 30))
        self.intervalSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.intervalSpinBox.setMinimum(-100)
        self.intervalSpinBox.setMaximum(100)
        self.intervalSpinBox.setObjectName("intervalSpinBox")
        self.verticalLayout_18.addWidget(self.intervalSplitter)
        self.tabWidget.addTab(self.transposeTab, "")
        self.mirrorTab = QtWidgets.QWidget()
        self.mirrorTab.setObjectName("mirrorTab")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.mirrorTab)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.positionVerticalLayout = QtWidgets.QVBoxLayout()
        self.positionVerticalLayout.setObjectName("positionVerticalLayout")
        self.positionLabel = QtWidgets.QLabel(self.mirrorTab)
        self.positionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.positionLabel.setObjectName("positionLabel")
        self.positionVerticalLayout.addWidget(self.positionLabel)
        self.positionComboBox = QtWidgets.QComboBox(self.mirrorTab)
        self.positionComboBox.setMinimumSize(QtCore.QSize(0, 30))
        self.positionComboBox.setMaximumSize(QtCore.QSize(16777215, 30))
        self.positionComboBox.setObjectName("positionComboBox")
        self.positionVerticalLayout.addWidget(self.positionComboBox)
        self.horizontalLayout_16.addLayout(self.positionVerticalLayout)
        self.axisVerticalLayout = QtWidgets.QVBoxLayout()
        self.axisVerticalLayout.setObjectName("axisVerticalLayout")
        self.axisLabel = QtWidgets.QLabel(self.mirrorTab)
        self.axisLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.axisLabel.setObjectName("axisLabel")
        self.axisVerticalLayout.addWidget(self.axisLabel)
        self.axisComboBox = QtWidgets.QComboBox(self.mirrorTab)
        self.axisComboBox.setMinimumSize(QtCore.QSize(0, 30))
        self.axisComboBox.setMaximumSize(QtCore.QSize(16777215, 30))
        self.axisComboBox.setObjectName("axisComboBox")
        self.axisVerticalLayout.addWidget(self.axisComboBox)
        self.horizontalLayout_16.addLayout(self.axisVerticalLayout)
        self.tabWidget.addTab(self.mirrorTab, "")
        self.repeatTab = QtWidgets.QWidget()
        self.repeatTab.setObjectName("repeatTab")
        self.repeatSplitter = QtWidgets.QSplitter(self.repeatTab)
        self.repeatSplitter.setGeometry(QtCore.QRect(18, 18, 809, 72))
        self.repeatSplitter.setOrientation(QtCore.Qt.Vertical)
        self.repeatSplitter.setObjectName("repeatSplitter")
        self.repeatLabel = QtWidgets.QLabel(self.repeatSplitter)
        self.repeatLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.repeatLabel.setObjectName("repeatLabel")
        self.repeatSpinBox = QtWidgets.QSpinBox(self.repeatSplitter)
        self.repeatSpinBox.setMinimumSize(QtCore.QSize(100, 30))
        self.repeatSpinBox.setMaximumSize(QtCore.QSize(16777215, 30))
        self.repeatSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.repeatSpinBox.setMinimum(1)
        self.repeatSpinBox.setMaximum(999999999)
        self.repeatSpinBox.setObjectName("repeatSpinBox")
        self.tabWidget.addTab(self.repeatTab, "")
        self.deviceFrame = QtWidgets.QFrame(self.controlsWidget)
        self.deviceFrame.setGeometry(QtCore.QRect(20, 0, 851, 210))
        self.deviceFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.deviceFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.deviceFrame.setObjectName("deviceFrame")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.deviceFrame)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.deviceWidget = QtWidgets.QWidget(self.deviceFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deviceWidget.sizePolicy().hasHeightForWidth())
        self.deviceWidget.setSizePolicy(sizePolicy)
        self.deviceWidget.setMinimumSize(QtCore.QSize(0, 80))
        self.deviceWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.deviceWidget.setObjectName("deviceWidget")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.deviceWidget)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.deviceHorizontalLayout = QtWidgets.QHBoxLayout()
        self.deviceHorizontalLayout.setObjectName("deviceHorizontalLayout")
        self.inputVerticalLayout = QtWidgets.QVBoxLayout()
        self.inputVerticalLayout.setObjectName("inputVerticalLayout")
        self.inputLabel = QtWidgets.QLabel(self.deviceWidget)
        self.inputLabel.setObjectName("inputLabel")
        self.inputVerticalLayout.addWidget(self.inputLabel)
        self.inputComboBox = QtWidgets.QComboBox(self.deviceWidget)
        self.inputComboBox.setMinimumSize(QtCore.QSize(0, 30))
        self.inputComboBox.setObjectName("inputComboBox")
        self.inputVerticalLayout.addWidget(self.inputComboBox)
        self.deviceHorizontalLayout.addLayout(self.inputVerticalLayout)
        self.outputVerticalLayout = QtWidgets.QVBoxLayout()
        self.outputVerticalLayout.setObjectName("outputVerticalLayout")
        self.outputLabel = QtWidgets.QLabel(self.deviceWidget)
        self.outputLabel.setObjectName("outputLabel")
        self.outputVerticalLayout.addWidget(self.outputLabel)
        self.outputComboBox = QtWidgets.QComboBox(self.deviceWidget)
        self.outputComboBox.setMinimumSize(QtCore.QSize(0, 30))
        self.outputComboBox.setObjectName("outputComboBox")
        self.outputVerticalLayout.addWidget(self.outputComboBox)
        self.deviceHorizontalLayout.addLayout(self.outputVerticalLayout)
        self.horizontalLayout_17.addLayout(self.deviceHorizontalLayout)
        self.verticalLayout_19.addWidget(self.deviceWidget)
        self.deviceRefreshHorizontalLayout = QtWidgets.QHBoxLayout()
        self.deviceRefreshHorizontalLayout.setObjectName("deviceRefreshHorizontalLayout")
        self.widget_9 = QtWidgets.QWidget(self.deviceFrame)
        self.widget_9.setObjectName("widget_9")
        self.deviceRefreshHorizontalLayout.addWidget(self.widget_9)
        self.deviceSelectButton = QtWidgets.QPushButton(self.deviceFrame)
        self.deviceSelectButton.setObjectName("deviceSelectButton")
        self.deviceRefreshHorizontalLayout.addWidget(self.deviceSelectButton)
        self.deviceRefreshButton = QtWidgets.QPushButton(self.deviceFrame)
        self.deviceRefreshButton.setObjectName("deviceRefreshButton")
        self.deviceRefreshHorizontalLayout.addWidget(self.deviceRefreshButton)
        self.widget_10 = QtWidgets.QWidget(self.deviceFrame)
        self.widget_10.setObjectName("widget_10")
        self.deviceRefreshHorizontalLayout.addWidget(self.widget_10)
        self.verticalLayout_19.addLayout(self.deviceRefreshHorizontalLayout)
        self.horizontalLayout.addWidget(self.controlsWidget)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.currentEffectsWidget = QtWidgets.QWidget(self.centralwidget)
        self.currentEffectsWidget.setMinimumSize(QtCore.QSize(900, 0))
        self.currentEffectsWidget.setMaximumSize(QtCore.QSize(900, 16777215))
        self.currentEffectsWidget.setObjectName("currentEffectsWidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.currentEffectsWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 40, 851, 511))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.currentEffectsList = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.currentEffectsList.setObjectName("currentEffectsList")
        self.verticalLayout_2.addWidget(self.currentEffectsList)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.verticalLayout_2.addLayout(self.horizontalLayout_19)
        self.removeEffectButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.removeEffectButton.setObjectName("removeEffectButton")
        self.verticalLayout_2.addWidget(self.removeEffectButton)
        self.horizontalLayout.addWidget(self.currentEffectsWidget)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SillyKeyboard"))
        self.volumeLabel.setText(_translate("MainWindow", "Volume (%)"))
        self.delayLabel.setText(_translate("MainWindow", "Delay (ms)"))
        self.addEffectButton.setText(_translate("MainWindow", "Add"))
        self.intervalLabel.setText(_translate("MainWindow", "Interval (half steps)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.transposeTab), _translate("MainWindow", "Transpose"))
        self.positionLabel.setText(_translate("MainWindow", "Position"))
        self.axisLabel.setText(_translate("MainWindow", "Axis"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mirrorTab), _translate("MainWindow", "Mirror"))
        self.repeatLabel.setText(_translate("MainWindow", "Time (ms)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.repeatTab), _translate("MainWindow", "Repeat"))
        self.inputLabel.setText(_translate("MainWindow", "Input"))
        self.outputLabel.setText(_translate("MainWindow", "Output"))
        self.deviceSelectButton.setText(_translate("MainWindow", "Select"))
        self.deviceRefreshButton.setText(_translate("MainWindow", "Refresh Devices"))
        self.removeEffectButton.setText(_translate("MainWindow", "Remove"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

